# Generated by Django 5.1.3 on 2025-01-13 14:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 14, 36, 7, 853775, tzinfo=datetime.timezone.utc), verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 14, 36, 7, 852742, tzinfo=datetime.timezone.utc), verbose_name='habit start date'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='title',
            field=models.CharField(default='New Challenge FELN8', max_length=40),
        ),
    ]
