# Generated by Django 5.1.3 on 2024-12-17 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='is_intensity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_multi_entry_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='habit start date'),
        ),
    ]
