# Generated by Django 5.1.3 on 2024-12-17 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_entry_date_habit_is_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 43, 32, 249990, tzinfo=datetime.timezone.utc), verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 43, 32, 213991, tzinfo=datetime.timezone.utc), verbose_name='habit start date'),
        ),
    ]
