# Generated by Django 5.1.3 on 2024-12-17 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_entry_date_alter_habit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 48, 4, 369925, tzinfo=datetime.timezone.utc), verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='intensity',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 48, 4, 338920, tzinfo=datetime.timezone.utc), verbose_name='habit start date'),
        ),
    ]
