# Generated by Django 5.1.3 on 2024-12-17 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_entry_date_alter_entry_entry_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 51, 51, 655072, tzinfo=datetime.timezone.utc), verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='intensity',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 51, 51, 625074, tzinfo=datetime.timezone.utc), verbose_name='habit start date'),
        ),
    ]
