# Generated by Django 5.1.3 on 2024-12-17 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_entry_date_alter_entry_entry_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 52, 58, 43183, tzinfo=datetime.timezone.utc), verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='intensity',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 9, 52, 58, 13177, tzinfo=datetime.timezone.utc), verbose_name='habit start date'),
        ),
    ]
