# Generated by Django 5.1.3 on 2024-12-17 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_entry_date_alter_entry_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='title',
            field=models.CharField(default='New Challenge 2EPYQ', max_length=40),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 10, 37, 26, 177173, tzinfo=datetime.timezone.utc), verbose_name='date of entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='entry',
            name='intensity',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 10, 37, 26, 146147, tzinfo=datetime.timezone.utc), verbose_name='habit start date'),
        ),
    ]
